### ISSUE TITLE
how to train new action?

### ISSUE THREAD

**Issue by ghost** [chinmayembedded/Human-Activity-Recognition#1]
thank you for greats job.
Can you tell me how to train a new model with new action?

**Comment by chinmayembedded** [comment]
For training on new activities,

- Dataset requirement can be explained on - 

https://tele-immersion.citris-uc.org/berkeley_mhad

- The openpose detections for a new activity can be stored in a CSV file with the label for an activity.

Check below repository for creating the dataset and retraining the model -
https://github.com/stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input/tree/master/data/HAR_pose_activities/database

- Keep the trained model based on above link in new_model folder
