### ISSUE TITLE
more complex human activities

### ISSUE THREAD

**Issue by kli017** [chinmayembedded/Human-Activity-Recognition#3]
Hello @chinmayembedded, nice work! actually I have tried the same work just as yours. This LSTM model works well on 2D human keypoints extracted on those 6 types simple human activities. I have tried on some more complex activities such as  running, walking, carrying etc and found the result does not well as those 6.. I was wondering have your tried any other model on other activities?

**Comment by chinmayembedded** [comment]
@kli017 I haven't tried other activities as the data set was too large. I need to add activities in the current implementation to check accuracy.
